### ISSUE TITLE
Operators, Patterns, Scheduling & Parallelism and Further Abstractions

### ISSUE THREAD

**Issue by sirinath** [strymonas/staged-streams.scala#3]
Also adding operators and patterns to combine and pipeline the streams would be needed. 

Think about:
- [ ] combinators
- [ ] transformers
- [ ] push and pull streams
- [ ] vectorised time series and linear algebra for ML
- [ ] streaming data through series, tables, panels, etc. for ML
- [ ] [Algorithmic Skeletons ](https://en.wikipedia.org/wiki/Algorithmic_skeleton) and [Process Calculi](https://en.wikipedia.org/wiki/Process_calculus) and Process Algebras

**Comment by biboudis** [comment]
Enhancing the strymonas libraries with more combinators, trasformers and investigating its applicability in larger domains such a machine learning is a top priority for us.

Since this issue is general and and does not provide a strong case for a single action item let's move this on gitter.

Concrete features requests are more than welcome! 
Thank you @sirinath
